import { ArrowRight, GitBranch, Mail, Send, Sparkles } from 'lucide-react'
import { motion } from 'framer-motion'
import { events, projects, technologies } from '@/constants/content'
import { Button, SectionHeading } from '@/components/ui/primitives'

const reveal = { initial: { opacity: 0, y: 24, filter: 'blur(8px)' }, whileInView: { opacity: 1, y: 0, filter: 'blur(0px)' }, viewport: { once: true, amount: 0.2 }, transition: { duration: 0.7 } }

export function Hero() {
  const scroll = (id: string) => document.querySelector(id)?.scrollIntoView({ behavior: 'smooth' })
  return <section id="home" className="relative mx-auto flex min-h-[calc(100svh-6rem)] max-w-6xl items-center px-5 pb-20 pt-24 sm:px-8"><div className="grid w-full items-center gap-12 lg:grid-cols-[1.15fr_.85fr]"><motion.div {...reveal}><p className="mb-6 flex items-center gap-2 text-xs uppercase tracking-[.24em] text-cyan-200/70"><Sparkles className="h-3.5 w-3.5" /> Digital product studio</p><h1 className="max-w-3xl text-balance text-6xl font-semibold leading-[.93] tracking-[-.075em] text-white sm:text-7xl lg:text-8xl">Placeholder <span className="text-gradient">Title</span></h1><p className="mt-7 max-w-xl text-pretty text-base leading-7 text-zinc-400 sm:text-lg">We create digital experiences for ideas that refuse to stay ordinary. Placeholder copy for a future team story.</p><div className="mt-9 flex flex-wrap gap-3"><Button onClick={() => scroll('#projects')}>Подробнее</Button><Button variant="secondary" onClick={() => scroll('#projects')}>Наши проекты</Button></div></motion.div><motion.div initial={{ opacity: 0, scale: .88 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 1, delay: .15 }} className="relative mx-auto aspect-square w-full max-w-md"><div className="absolute inset-[13%] rounded-full border border-cyan-200/15 bg-cyan-400/[.03] shadow-[0_0_100px_rgba(0,212,255,.15)]" /><div className="absolute inset-[23%] rounded-[2rem] border border-violet-300/30 bg-gradient-to-br from-cyan-300/20 via-transparent to-violet-500/30 backdrop-blur-sm motion-safe:animate-[spin_18s_linear_infinite]" /><div className="absolute inset-[33%] grid place-items-center rounded-full bg-gradient-to-br from-cyan-200 to-violet-500 text-4xl text-black shadow-[0_0_70px_rgba(124,58,237,.45)]">✦</div><div className="absolute left-0 top-1/3 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-cyan-100 backdrop-blur-md">Build / 01</div><div className="absolute bottom-1/4 right-0 rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-violet-100 backdrop-blur-md">Future ready</div></motion.div></div></section>
}

export function Projects() {
  return <section id="projects" className="mx-auto max-w-6xl px-5 py-28 sm:px-8"><motion.div {...reveal}><SectionHeading eyebrow="Selected work" title={<>Наши <span className="text-gradient">проекты</span></>} description="Здесь появятся кейсы, которые расскажут о задаче, процессе и измеримом результате." /></motion.div><div className="mt-12 grid gap-4 md:grid-cols-3">{projects.map((project, i) => <motion.article key={project.number} {...reveal} transition={{ duration: .65, delay: i * .08 }} className="group overflow-hidden rounded-2xl border border-white/10 bg-[#0d1117]/75 p-4 transition hover:-translate-y-1 hover:border-cyan-200/30 hover:shadow-[0_16px_60px_rgba(0,212,255,.08)]"><div className={`relative aspect-[1.15] overflow-hidden rounded-xl bg-gradient-to-br ${project.tone}`}><span className="absolute left-4 top-4 font-mono text-xs text-white/60">{project.number}</span><div className="absolute inset-x-5 bottom-5 h-px bg-gradient-to-r from-transparent via-white/50 to-transparent transition duration-500 group-hover:scale-x-150" /></div><div className="px-2 pb-2 pt-5"><h3 className="text-xl font-medium text-white">{project.title}</h3><p className="mt-3 text-sm leading-6 text-zinc-400">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.tags.map(tag => <span key={tag} className="rounded-full border border-white/10 px-2.5 py-1 text-[11px] text-zinc-300">{tag}</span>)}</div><button className="mt-6 flex items-center gap-2 text-sm text-cyan-100">View placeholder <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></button></div></motion.article>)}</div></section>
}

export function TechStack() {
  return <section id="stack" className="mx-auto max-w-6xl px-5 py-28 sm:px-8"><motion.div {...reveal}><SectionHeading eyebrow="Crafted with precision" title={<>Наш <span className="text-gradient">стек</span></>} description="Инструменты, которые станут основой для будущих продуктов и экспериментов." /></motion.div><div className="mt-12 grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">{technologies.map((tech, i) => <motion.div key={tech} {...reveal} transition={{ duration: .45, delay: Math.min(i * .025, .35) }} className="group rounded-xl border border-white/10 bg-white/[.025] px-4 py-4 text-sm text-zinc-300 transition hover:scale-[1.025] hover:border-cyan-200/30 hover:bg-cyan-300/[.05] hover:text-white"><span className="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-violet-400 transition group-hover:bg-cyan-300 group-hover:shadow-[0_0_9px_#00d4ff]" />{tech}</motion.div>)}</div></section>
}

export function Events() {
  return <section id="events" className="mx-auto max-w-6xl px-5 py-28 sm:px-8"><motion.div {...reveal}><SectionHeading eyebrow="In motion" title={<>Мероприятия и <span className="text-gradient">события</span></>} /></motion.div><div className="mt-12 border-l border-white/10 pl-6 sm:pl-10">{events.map((event, i) => <motion.article key={event.title} {...reveal} transition={{ duration: .6, delay: i * .1 }} className="relative mb-10 last:mb-0"><span className="absolute -left-[31px] top-1 h-3 w-3 rounded-full border-2 border-[#05060a] bg-cyan-300 shadow-[0_0_14px_#00d4ff] sm:-left-[47px]" /><p className="font-mono text-xs tracking-wider text-cyan-200/70">{event.date}</p><div className="mt-3 rounded-2xl border border-white/10 bg-white/[.025] p-5 transition hover:border-violet-300/30 hover:bg-white/[.04]"><h3 className="text-lg font-medium text-white">{event.title}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-zinc-400">{event.description}</p><button className="mt-4 text-sm text-violet-200">Подробнее →</button></div></motion.article>)}</div></section>
}

export function Footer() {
  return <footer id="contacts" className="border-t border-white/10 px-5 py-14 sm:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-10 md:flex-row md:items-end md:justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-cyan-200/70">Let’s make an impact</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.05em] text-white">Placeholder contact.</h2><a className="mt-5 inline-block text-zinc-400 transition hover:text-white" href="mailto:hello@example.com">hello@example.com</a></div><div className="flex gap-3">{[{ icon: Send, label: 'Telegram' }, { icon: GitBranch, label: 'GitHub' }, { icon: Mail, label: 'Email' }].map(({ icon: Icon, label }) => <a key={label} href="#contacts" aria-label={label} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 text-zinc-300 transition hover:border-cyan-200/40 hover:bg-cyan-300/10 hover:text-cyan-100"><Icon className="h-4 w-4" /></a>)}</div></div><div className="mx-auto mt-12 max-w-6xl border-t border-white/10 pt-5 text-xs text-zinc-600">© {new Date().getFullYear()} HATOMS. Placeholder portfolio.</div></footer>
}
